### ISSUE TITLE
File is 10Bit error?

### ISSUE THREAD

**Issue by sinnx3** [ThoughtfulDev/Anime4K#2]
running (cpu):
 `python3 Anime4K.py -m shader --shader_dir "./shaders" --width 3840 --height 2160 -i input.mkv --output x264_upscale.mkv`

results in:
`File is 10Bit
Traceback (most recent call last):
  File "Anime4K.py", line 54, in <module>
    shader(fn, args['width'], args['height'], args['shader_dir'], args['bit'], outname)
  File "/home/sinnx3/Anime4K/shader.py", line 281, in shader
    cpu_shader(fn, width, height, shader, ten_bit, outname, files=files)
  File "/home/sinnx3/Anime4K/shader.py", line 384, in cpu_shader
    _m = MediaInfo.parse(fn)
  File "/home/sinnx3/.local/lib/python3.8/site-packages/pymediainfo/__init__.py", line 421, in parse
    lib, handle, lib_version_str, lib_version = cls._get_library(library_file)
  File "/home/sinnx3/.local/lib/python3.8/site-packages/pymediainfo/__init__.py", line 323, in _get_library
    raise OSError("Failed to load library")
OSError: Failed to load library
sinnx3@DESKTOP-D3LHBKG:~/Anime4K$
`

running (gpu):
`python3 Anime4K.py -m shader --shader_dir "./shaders" --width 3840 --height 2160 -i input.mkv --output x264_upscale.mkv`

`File is 10Bit
Traceback (most recent call last):
  File "Anime4K.py", line 54, in <module>
    shader(fn, args['width'], args['height'], args['shader_dir'], args['bit'], outname)
  File "/home/sinnx3/Anime4K/shader.py", line 283, in shader
    gpu_shader(fn, width, height, shader, ten_bit, outname, files=files)
  File "/home/sinnx3/Anime4K/shader.py", line 305, in gpu_shader
    _m = MediaInfo.parse(fn)
  File "/home/sinnx3/.local/lib/python3.8/site-packages/pymediainfo/__init__.py", line 421, in parse
    lib, handle, lib_version_str, lib_version = cls._get_library(library_file)
  File "/home/sinnx3/.local/lib/python3.8/site-packages/pymediainfo/__init__.py", line 323, in _get_library
    raise OSError("Failed to load library")
OSError: Failed to load library
`

**Comment by sinnx3** [comment]
And then if source file is not 10 bit....

running (cpu):
`python3 Anime4K.py -m shader --shader_dir "./shaders" --width 3840 --height 2160 -i input.mkv --output x264_upscale.mkv`

`File is not 10Bit
Traceback (most recent call last):
  File "Anime4K.py", line 54, in <module>
    shader(fn, args['width'], args['height'], args['shader_dir'], args['bit'], outname)
  File "/home/sinnx3/Anime4K/shader.py", line 281, in shader
    cpu_shader(fn, width, height, shader, ten_bit, outname, files=files)
  File "/home/sinnx3/Anime4K/shader.py", line 384, in cpu_shader
    _m = MediaInfo.parse(fn)
  File "/home/sinnx3/.local/lib/python3.8/site-packages/pymediainfo/__init__.py", line 421, in parse
    lib, handle, lib_version_str, lib_version = cls._get_library(library_file)
  File "/home/sinnx3/.local/lib/python3.8/site-packages/pymediainfo/__init__.py", line 323, in _get_library
    raise OSError("Failed to load library")
OSError: Failed to load library
`

running (gpu):
`python3 Anime4K.py -m shader --shader_dir "./shaders" --width 3840 --height 2160 -i input.mkv --output x264_upscale.mkv`

`
File is not 10Bit
Traceback (most recent call last):
  File "Anime4K.py", line 54, in <module>
    shader(fn, args['width'], args['height'], args['shader_dir'], args['bit'], outname)
  File "/home/sinnx3/Anime4K/shader.py", line 283, in shader
    gpu_shader(fn, width, height, shader, ten_bit, outname, files=files)
  File "/home/sinnx3/Anime4K/shader.py", line 305, in gpu_shader
    _m = MediaInfo.parse(fn)
  File "/home/sinnx3/.local/lib/python3.8/site-packages/pymediainfo/__init__.py", line 421, in parse
    lib, handle, lib_version_str, lib_version = cls._get_library(library_file)
  File "/home/sinnx3/.local/lib/python3.8/site-packages/pymediainfo/__init__.py", line 323, in _get_library
    raise OSError("Failed to load library")
OSError: Failed to load library
`

**Comment by sinnx3** [comment]
To clarify even further, this is being run in a WSL 20.04 x64 instance

**Comment by ThoughtfulDev** [comment]
Did you install the dependencies? The error comes from pymediainfo which itself requires mediainfo (apt install mediainfo).

What you need:

- mpv > 0.32
- ffmpeg
- mkvnixtool
- mediainfo
- A dedicated GPU (no VM) [AMD/NVIDIA/Intel] (regardless of if you use cpu or gpu (thats just the codec))

so even if you fix it you still need a gpu to apply the mpv shaders. (within mpv).

**Comment by sinnx3** [comment]
made it past the initial issue however.... leads to a secondary EOF which happens on both wsl and ubuntu 20.04 with a GTX 1070TI and drivers installed

```
File: temp.mkv
Using the following shaders:
./shaders/Anime4K_Denoise_Bilateral_Median.glsl:./shaders/Anime4K_Deblur_DoG.glsl:./shaders/Anime4K_DarkLines_HQ.glsl:./shaders/Anime4K_ThinLines_HQ.glsl:./shaders/Anime4K_Upscale_CNN_UL_x2_Deblur.glsl
Encoding with preset: veryslow
Option vf-append: vapoursynth doesn't exist.
Error parsing option vf-append (option parameter could not be parsed)
/home/sinnx3/.config/mpv/mpv.conf:133: setting option vf-append='@ivtc:vapoursynth="~~/vs/ivtc.vpy":buffered-frames=5:concurrent-frames=5' failed.
Option vf-remove: item label @ivtc not found.
Option vf-append: vapoursynth doesn't exist.
Error parsing option vf-append (option parameter could not be parsed)
/home/sinnx3/.config/mpv/mpv.conf:138: setting option vf-append='@deinterlace:vapoursynth="~~/vs/deinterlace.vpy":buffered-frames=5:concurrent-frames=5' failed.
Option vf-remove: item label @deinterlace not found.
Option vf-append: vapoursynth doesn't exist.
Error parsing option vf-append (option parameter could not be parsed)
/home/sinnx3/.config/mpv/mpv.conf:153: setting option vf-append='@warpsharp:vapoursynth="~~/vs/warpsharp.vpy":buffered-frames=3:concurrent-frames=4' failed.
Option vf-remove: item label @warpsharp not found.
Option vf-append: vapoursynth doesn't exist.
Error parsing option vf-append (option parameter could not be parsed)
/home/sinnx3/.config/mpv/mpv.conf:162: setting option vf-append='@simulcast:vapoursynth="~~/vs/simulcast.vpy":buffered-frames=3:concurrent-frames=4' failed.
Option vf-remove: item label @simulcast not found.
[auto_profiles] Applying auto profile: nonsimulcast-autoprofile 
Option vf-remove: item label @simulcast not found.
 (+) Video --vid=1 (*) 'Rom & Rem H265' (hevc 1920x1080 23.976fps)
[gpu] This is experimental. Keep in mind:
[gpu]  - OSD rendering is done in software.
[gpu]  - Encoding will convert the RGB output to yuv420p in software.
[gpu]  - Using this with --vo=gpu will filter the video twice!
[gpu]    (And you can't prevent this; they use the same options.)
[gpu]  - Some features are simply not supported.
[autoconvert] Converting rgb0 -> yuv444p
VO: [lavc] 3840x2160 yuv444p
[vo/lavc] Opening encoder: libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 [libx264]
[ffmpeg] libx264: ignoring invalid SAR: 0/0
x264 [error]: invalid preset 'veryslow:level=6.1:crf=17:aq-mode=3:psy-rd=1.0:bf=6'
[ffmpeg] libx264: Error setting preset/tune veryslow:level=6.1:crf=17:aq-mode=3:psy-rd=1.0:bf=6/(null).
[vo/lavc] Could not initialize encoder.
Could not initialize video chain.
Video: no video

[encode] no data written to target file
Exiting... (Interrupted by error)
sinnx3@sinnx3-MS-7A38:~/Anime4K$ 
```

**Comment by ThoughtfulDev** [comment]
Should be fixed in newest commit 👍🏻 
Apparently there was a syntax change ":" => ",".

Please try again now.

**Comment by RanjeetEppa18** [comment]
Any idea why this error?

with CPU processing (WSL) -
![image](https://user-images.githubusercontent.com/52062425/131221399-636d9d0d-3b5c-414f-96f0-86ff8e1c8347.png)

**Comment by ThoughtfulDev** [comment]
It probably wont work in WSL because as i said you need dedicated gpu + this has been only tested using linux
