### ISSUE TITLE
missing lib in readme.md

### ISSUE THREAD

**Issue by bjuergens** [ThoughtfulDev/Anime4K#3]
heyo, 

Thank you for making this. You did the world a great service :D

_____

The readme.md is missing some information in the "Installing / Getting started" section. One also needs to install `libmediainfo-dev`and `mkvtoolnix`, e.g. on ubuntu: `sudo apt install libmediainfo-dev mkvtoolnix`

____

on a side note: some instructions on how to do upscaling by a definied ratio (e.g. times two) or how to upscale while keeping aspect-ration would be nice to have, especially since older shows tend to have different aspect ratios than 1080p et al. So simply upscaling to 3840 x 2160 will (probably?) introduce distortion

For now I just use ffprobe, and then calculated the height and width manually, but the command for ffprobe is a bit clunky, so having an option for it, would be very convinient. The command looks something like this: `fprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=s=x:p=0 \[Reaktor\]\ GTO\ -\ Great\ Teacher\ Onizuka\ -\ E02\ \[576p\]\[x265\]\[10-bit\].mkv`

**Comment by ThoughtfulDev** [comment]
Hello,
thank you.

The "what you need" block does include mediainfo/mkvtoolnix but i add it explicitly later.

Regarding the aspect ratio: You can define the width and height yourself when upscaling using the --width and --height parameters.
