### ISSUE TITLE
gpu error

### ISSUE THREAD

**Issue by m-ziglioli** [ThoughtfulDev/Anime4K#4]
Hi, even if in the requirements list there is "A dedicated GPU (no VM) [AMD/NVIDIA/Intel]" I need it also when I use only cpu encoding? 
I get these errors: 
[gpu] Could not initialize EGL.
[gpu] Could not create offscreen ra context.
[user_filter_wrapper] Creating filter 'gpu' failed.
[vo/lavc] error encoding at EOF
Video: no video
No video or audio streams selected.

[encode] no data written to target file

I'm launching commands in ubuntu shell on windows.

**Comment by monoletP** [comment]
Hello, I met the same error. Did you solve the problem?

**Comment by m-ziglioli** [comment]
I have installed ubuntu on external hard disk. It should also work on a virtual machine, but is is slower
